apiVersion: v1
kind: Namespace
metadata:
  name: ping-pong
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: josephshih13/ping-pong
          env:
          - name: DB_URL
            value: "postgresql://postgres:example@postgres-svc.ping-pong:5432/postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: ping-pong
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 6789
      protocol: TCP
      targetPort: 9936
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ping-pong-ingress
  namespace: ping-pong
spec:
  rules:
  - http:
      paths:
      - path: /pong
        backend:
          serviceName: ping-pong-svc
          servicePort: 6789
      - path: /internal
        backend:
          serviceName: ping-pong-svc
          servicePort: 6789
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: ping-pong
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: ping-pong
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.0
          ports:
            - name: postgres
              containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "example"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi